### ISSUE TITLE
Not all components are working

### ISSUE THREAD

**Issue by xemil** [crossplatformsweden/react-native-components#2]
Not all components are rendered. 

1. react-native init MyApp --template typescript && node MyApp/setup.js
2.  npm i react-native-vector-icons@4.5.0 react-native-paper react-native-cross-components && react-native link
3. Add components to App.tsx

Suggestion add: 
`npm i react-native-vector-icons@4.5.0 react-native-paper react-native-cross-components && react-native link react-native-vector-icons` to postinstall in package.json? hardcode correct paper version?

**Comment by thomashagstrom** [comment]
Fixed
